"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { Dongle } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import "tw-elements/dist/css/tw-elements.min.css";
// const inter = Inter({ subsets: ["latin"], weight: ["300"] });
const dongle = Dongle({ subsets: ["latin"], weight: ["300"] });

const metadata = {
  title: "Post Your Biz",
  description: "Generated by kirollos sawiers",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dongle.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
